from typing import Any

class HolderError(RuntimeError): ...

class Context:
    def __init__(self, data_dir: str, schema_sql: str) -> None: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def create_project(self, name: str) -> dict[str, Any]: ...
    def list_projects(self) -> list[dict[str, Any]]: ...
    def create_card(
        self,
        project_id: str,
        title: str,
        content: str | None = None,
        parent_card_id: str | None = None,
    ) -> dict[str, Any]: ...
    def list_cards(self, project_id: str) -> list[dict[str, Any]]: ...
    def list_links(self, card_id: str) -> dict[str, Any]: ...
    def add_link(
        self, from_card_id: str, to_card_id: str, kind: str,
        label: str | None = None,
    ) -> list[dict[str, Any]]: ...
    def remove_link(self, from_card_id: str, to_card_id: str, kind: str) -> None: ...
    def list_complete_cards_page(
        self, project_id: str, cursor: str | None = None, limit: int = 256
    ) -> dict[str, Any]: ...
    def get_card_content(self, card_id: str) -> str: ...
    def update_card(
        self, card_id: str, content: str, title: str | None = None
    ) -> dict[str, Any]: ...
    def __enter__(self) -> Context: ...
    def __exit__(self, *exc_info: object) -> None: ...
